server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # GLOBAL RATE LIMITER CONFIGURATION (Protects all routes below)
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10 # Number of allowed requests per second
            redis-rate-limiter.burstCapacity: 20 # Maximum burst allowed in a single second
            redis-rate-limiter.requestedTokens: 1 # Tokens consumed per request
            key-resolver: "#{@userIpKeyResolver}" # Bean name for IP-based tracking

      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/api/v1/tariffs/**"
        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/api/v1/subscriptions/**"
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/api/v1/customers/**"
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/api/v1/notifications/**"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/telecom-realm

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      use-pkce-with-authorization-code-grant: true
    urls:
      - name: Customer Service
        url: /v3/api-docs/customer-service
      - name: Subscription Service
        url: /v3/api-docs/subscription-service
      - name: Catalog Service
        url: /v3/api-docs/catalog-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
logging:
  level:
    org.springframework.security: DEBUG