# config-repo/notification-service.yml
server:
  port: 8085

spring:
  application:
    name: notification-service
  kafka:
    consumer:
      group-id: notification-service
      properties:
        # Explicitly tell the consumer to map incoming JSON to this specific Event class
        spring.json.value.default.type: com.telecom.notification_service.event.SubscriptionCreatedEvent
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/telecom-realm
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: notification_schema
        hbm2ddl.create_namespaces: true
  flyway:
    enabled: true
    schemas: notification_schema
    default-schema: notification_schema
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0

notification:
  mock:
    fail: false
    latency-ms: 250
  textbee:
    api-url: "https://api.textbee.dev/api/v1"
    api-key: "your-api-key"
    device-id: "your-device-id"

resilience4j:
  circuitbreaker:
    instances:
      notificationProvider:
        sliding-window-size: 4
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 20s
        record-exceptions:
          - com.telecom.notification_service.exception.NotificationDispatchException

