spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: payment_schema # JPA will use this schema
        hbm2ddl.create_namespaces: true

logging:
  level:
    com.telecom.payment_service: INFO
