server:
  port: 8084
spring:
  application:
    name: customer-service

  config:
    import: "classpath:application-shared.yml"

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/telecom_db}
    username: ${POSTGRES_USER:telecom_user}
    password: ${POSTGRES_PASSWORD:telecom_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: customer_schema
        hbm2ddl.create_namespaces: true

  flyway:
    enabled: true
    schemas: customer_schema
    default-schema: customer_schema
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0