spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/telecom-realm

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  opentelemetry:
    tracing:
      enabled: true
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces
      sampling:
        probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false